version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
platform: x64
clone_folder: C:\vowpal_wabbit
cache:
  - vowpalwabbit\packages -> **\packages.config
# need to install nuget packages before Visual Studio starts to make ANTLR targets available.
build_script:
# Temporary workaround: https://github.com/Microsoft/vcpkg/issues/4189#issuecomment-417462822
- rd /s /q C:\OpenSSL-v11-Win32
- rd /s /q C:\OpenSSL-v11-Win64
# Set up vowpal_wabbit repo root
- SET vwRoot=C:\vowpal_wabbit
# Set up toolchain integration
#- SET "msbuildPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
- SET nugetPath=%vwRoot%\vowpalwabbit\.nuget\nuget
# Restore and build
- cd %vwRoot%
- git submodule update --init --recursive
- .scripts/restore.cmd
- .scripts/build.cmd /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- ps: >-
    if($env:PLATFORM -eq "x64")
    {
       cd c:\vowpal_wabbit
       vstest.console /logger:Appveyor /Platform:x64 /inIsolation vowpalwabbit\AnyCPU\Release\cs_unittest.dll /TestCaseFilter:"TestCategory!=NotOnVSO"
    }
on_failure:
- ps: Get-ChildItem C:\Users\appveyor\AppData\Local\CrashDumps\\*.dmp | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
