version: 1.0.{build}
#os: Windows Server 2012 R2 # Per https://www.appveyor.com/docs/appveyor-yml/, os: is not a supported property to configure environment.
image: Visual Studio 2017
configuration:
- Release
platform: x64
clone_folder: C:\vowpal_wabbit
cache:
  - vowpalwabbit\packages -> **\packages.config
# need to install nuget packages before Visual Studio starts to make ANTLR targets available.
build_script:
# Temporary workaround: https://github.com/Microsoft/vcpkg/issues/4189#issuecomment-417462822
- rd /s /q C:\OpenSSL-v11-Win32
- rd /s /q C:\OpenSSL-v11-Win64
# Set up vowpal_wabbit repo root
- SET vwRoot=C:\vowpal_wabbit
# Set up toolchain integration
- SET nugetPath=%vwRoot%\vowpalwabbit\.nuget\nuget
# Restore and build
- cd %vwRoot%
- git submodule update --init --recursive
- .scripts/restore.cmd
- .scripts/build.cmd
test_script:
- ps: >-
    cd c:\vowpal_wabbit
    bin\Release\ds_explore_cs_test.exe test\explore\test1-input.txt test\explore\test1-expected.txt
    if($env:PLATFORM -eq "x64")

    {
       vstest.console /Platform:x64 /inIsolation vowpalwabbit\x64\Release\cs_unittest.dll /TestCaseFilter:"TestCategory!=NotOnVSO"
    }
on_failure:
- ps: Get-ChildItem C:\Users\appveyor\AppData\Local\CrashDumps\\*.dmp | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
