version: 1.0.{build}
os: Windows Server 2012 R2
configuration:
- Release
platform: x64
shallow_clone: true
clone_folder: C:\vowpal_wabbit
# need to install nuget packages before Visual Studio starts to make ANTLR targets available.
build_script:
- cd c:\vowpal_wabbit
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs_unittest\packages.config
- "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "C:\vowpal_wabbit\vowpalwabbit\vw.sln" /m /verbosity:normal
- cd c:\vowpal_wabbit\cs
- ..\vowpalwabbit\.nuget\nuget pack cs.csproj -Prop "Configuration=Release;Platform=x64" -Prop SolutionDir=..\vowpalwabbit\ -OutputDirectory bin\x64\Release
test_script:
- ps: >-
    if($env:PLATFORM -eq "x64")

    {
       vstest.console /logger:Appveyor /Platform:x64 /inIsolation c:\vowpal_wabbit\cs_unittest\bin\x64\Release\cs_unittest.dll
    }
